name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: action/setup-node@v3

      - name: Install Depedencies
        run: npm Install

      - name: Run Tests
        run: npm test 
